name: Descripting - Ali Ismayilov's blog
markdown: kramdown
url: http://alii.pro
short_url: alii.pro
exclude: ['Gemfile', 'Gemfile.lock', 'CNAME']
sass:
  sass_dir: assets/scss
  style: :compressed
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji
permalink: pretty
