name: Ali Ismayilov - professional page
markdown: redcarpet
url: alii.pro
exclude: ['Gemfile', 'Gemfile.lock', 'CNAME']
sass:
  sass_dir: assets/scss
  style: :compressed
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
